[package]
name = "waveutil-rs"
version = "0.1.0"
edition = "2023"

[dependencies]
windows-dll = "0.4.0"
winapi = { version = "0.3.9", features = ["processthreadsapi"] }
sysinfo = "0.24.3"
nwg = {version = "^1.0.12", package = "native-windows-gui"}
livesplit-hotkey = "0.6.0"
toml = "0.5"
serde = {version = "1.0.136"}

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "^0.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true